# This playbook fetches all the volumes whose name matches the regex pattern.
---
- name: Volumes whose names match the regex pattern
  hosts: localhost
  connection: local
  vars:
   creds:
    - array_ip: 10.10.1.1
      user: admin
      password: pass123
      validate_certs: false
      pattern: looky
    - array_ip: 192.168.2.33
      user: admin
      password: word987
      validate_certs: false
      pattern: aboutface


  tasks:
    - name: Get the details of all the Volumes
      dellemc.powerstore.info:
        array_ip: "{{ item.array_ip }}"
        user: "{{ item.user }}"
        password: "{{ item.password }}"
        validate_certs: "{{ item.validate_certs }}"
        gather_subset:
          - vol
      register: subset_result
      loop: "{{ creds }}" 

    # The set_fact generates a list of the volume names using the details of volumes(the output of the previous task).
    - name: Set fact
      ansible.builtin.set_fact:
        all_volumes_names: "{{ subset_result['Volumes'] | map(attribute='name') | list }}"

    # This task gets the list of the volumes which match a regular expression. The syntax of the regular expression is same as in python.
    - name: List of the all the volume names which match the pattern
      ansible.builtin.debug:
        msg: "{{ all_volumes_names | select('match', pattern) | list }}"
