---
- name: Query ISS api with Ansible
  hosts: localhost
  gather_facts: no     # set to true by default, runs the "setup" module
  
    
  tasks:
  - name: Print out to the screen
    uri:
      url: http://api.open-notify.org/iss-now.json
    register: astrojson     # the "register" keyword is not part of the uri module
                              # just like the "become" keyword, this augments how a module executes
                              # in this case, we want to save the response returned by this module
                              # ALL modules in Ansible return data. Think of it as the "results" of how the
                              # task ran.
                              
  - name: Display the contents of the variable astrojson
    debug:
      var: astrojson                                         

  - name: display the latitude from astrojson
    debug:
      var: astrojson['json']['iss_position']['latitude']

  - name: display the longitude from astrojson
    debug:
      var: astrojson['json']['iss_position']['longitude']

  - name: display the date time info 
    debug:
      var: astrojson['date']

  - name: Display the contents of the variable astrojson
    debug:
      msg: "refreshing"
    when: astrojson.get('gatorade', "baja blast") == "baja blast"

  - name: display the latitude from astrojson
    debug:
      var: astrojson['json']['iss_position']['latitude'].split(".")[0]

  - name: display the latitude from astrojson
    debug:
      var: astrojson.json.iss_position.latitude | regex_replace('\..*$', '')

  - name: display the longitude from astrojson
    debug:
      var: astrojson['json']['iss_position']['longitude'].split(".")[1]

  - name: display the status code
    debug:
      var: astrojson.status
