---              
- name: Deploy mission critical app  
  hosts: planetexpress
  gather_facts: True
  connection: ssh

  tasks:

  - name: debian or redhat specific tasks
    ansible.builtin.include_tasks: "tasks/{{ ansible_os_family.lower() }}.yml"
    when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
   
    #- name: redhat specific tasks
    #  ansible.builtin.import_tasks: tasks/debian.yml
    #  when: ansible_os_family == "Debian"

    #- name: redhat specific tasks
    #  ansible.builtin.import_tasks: tasks/redhat.yml
    #  when: ansible_os_family == "RedHat"

  - name: Get all home directories across all systems
    ansible.builtin.command: ls /home
    become: yes
    register: homevarz
    
  - name: Create a README.txt file if it does not exist in every home user directory
    ansible.builtin.lineinfile:
      create: yes
      path: /home/{{ item }}/README.txt
      line: "Type cowsay 'Moo, my good sir' for a funny display. Use CTRL + C to quit"
    loop: "{{ homevarz.stdout_lines }}"
    become: yes

